site_name: AAWS - User Guide
site_url: https://unrealid.github.io/aaws/
site_dir: public
nav:
  - Home: index.md
  - Release Notes: release_notes.md
  - Tools & Software: 
    - Tools: requirement.md
    - Software: software.md
  - Power System: 
    - Schemas: power.md
    - Wiring: solar-panel.md
  - Sensors:
    - Wind 10m: wind10.md
    - Wind 2m: wind2.md
    - Solar Radiation: radiation.md
    - T/RH : trh.md
    - Air Pressure: pressure.md
    - Wind 0.5m: wind05.md
    - Precipitation: rain.md
    - Evaporation: evaporation.md
    - Soil: soil.md
  - Data Logger: logger.md
  - Modems:
    - Moxa: modem.md
    - Robustel: modem.md
    - InHand: modem.md
theme: 
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - instant
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
extra:
  generator: false
copyright: Copyright &copy; 2020 SIRK BMKG