site_name: AAWS - User Guide
site_url: https://unrealid.github.io/aaws/
site_dir: public
nav:
  - Home: index.md
  - Getting Started: 
    - Tools: requirement.md
    - Software: software.md
  - Power System: 
    - Schemas: power.md
    - Wiring: solar-panel.md
  - Sensors:
    - Wind 10m: wind10.md
    - Wind 2m: wind2.md
    - Solar Radiation: radiation.md
    - T/RH : trh.md
    - Air Pressure: pressure.md
    - Wind 0.5m: wind05.md
    - Precipitation: rain.md
    - Evaporation: evaporation.md
    - Soil: soil.md
  - Data Logger: 
    - dEX-2: dex.md
    - DeTransfer: detransfer.md
    - Data Taker: logger.md
    - Battery Replacement: battery.md
  - Modems: modem.md
theme: 
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - instant
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2020 SIRK BMKG